arch:
  - amd64
os: linux
dist: jammy
git:
  depth: false

language: bash

services:
  - docker

before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.17.1/buildx-v0.17.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  
script:
  - docker login -u="moussavdb" --password-stdin <<< "$DOCKER_PASSWORD";
  - docker buildx create --use
  - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag moussavdb/build-java:21 --tag moussavdb/build-java:lts .
