dist: focal

git:
  depth: false

os: linux
language: generic

services:
  - docker
  
arch:
  - amd64
  - arm64  

before_install:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  if: arch = amd64
  - docker build -t moussavdb/build-java-$TRAVIS_CPU_ARCH:17 --build-arg URL_ARCH=x86_64 .
  if: arch = arm64
  - docker build -t moussavdb/build-java-$TRAVIS_CPU_ARCH:17 --build-arg URL_ARCH=aarch64 .

script:
  - docker images moussavdb/build-java-$TRAVIS_CPU_ARCH
  
after_success:
  - docker push moussavdb/build-java-$TRAVIS_CPU_ARCH:17;

