dist: jammy

git:
  depth: false

os: linux
language: generic

services:
  - docker

before_install:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  - docker build -t moussavdb/build-java:17 .
script:
  - docker images moussavdb/build-java
  
after_success:
  - docker push moussavdb/build-java:17;

