sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/build-java:17 -t moussavdb/build-java:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/build-java
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/build-java:17;
    docker push moussavdb/build-java:build_$TRAVIS_BUILD_NUMBER;

